<h1 style='font-size: 25px; color: crimson; font-family: Colonna MT; font-weight: 600; text-align: center'>Dataset Synthesis</h1>

---

<h1 style='font-size: 18px;  font-weight: 600'>2.0: Import Required Libraries</h1>

In [8]:
import numpy as np
import pandas as pd

def generate_soil_data(n_per_plot=50, n_plots=5):
    np.random.seed(42)
    total_records = n_per_plot * n_plots
    plot_ids = np.repeat([f"Plot {i+1}" for i in range(n_plots)], n_per_plot)

    data = {
        "Plot ID": plot_ids,
        "Soil pH": np.round(np.random.normal(6.5, 0.5, total_records), 2),
        "Organic Matter (%)": np.round(np.random.normal(2.8, 0.6, total_records), 2),
        "Nitrogen (%)": np.round(np.random.normal(0.25, 0.05, total_records), 3),
        "Phosphorus (mg/kg)": np.round(np.random.normal(18, 5, total_records), 1),
        "Potassium (cmol/kg)": np.round(np.random.normal(0.8, 0.2, total_records), 2),
        "Calcium (cmol/kg)": np.round(np.random.normal(10, 3, total_records), 2),
        "Magnesium (cmol/kg)": np.round(np.random.normal(1.5, 0.3, total_records), 2),
        "Sulfur (mg/kg)": np.round(np.random.normal(12, 3, total_records), 1),
        "Zinc (mg/kg)": np.round(np.random.normal(1.2, 0.4, total_records), 2),
        "Iron (mg/kg)": np.round(np.random.normal(100, 20, total_records), 1),
    }
    return pd.DataFrame(data)

soil_df = generate_soil_data(n_per_plot=50, n_plots=5)
sample_df = soil_df.groupby("Plot ID").sample(n=30, random_state=1).reset_index(drop=True)
sample_df.to_csv("Soil Health Data.csv", index=False)

In [9]:
display(sample_df)

,Plot ID,Soil pH,Organic Matter (%),Nitrogen (%),Phosphorus (mg/kg),Potassium (cmol/kg),Calcium (cmol/kg),Magnesium (cmol/kg),Sulfur (mg/kg),Zinc (mg/kg),Iron (mg/kg)
0,Plot 1,6.69,2.44,0.252,16.8,0.82,11.18,1.96,11.9,1.70,77.0
1,Plot 1,5.89,1.63,0.252,23.4,1.11,6.01,1.02,7.6,2.30,109.2
2,Plot 1,6.87,2.68,0.292,20.1,1.14,11.17,1.49,6.4,0.92,134.8
3,Plot 1,5.84,2.97,0.300,17.6,0.84,6.69,1.15,13.0,1.19,88.0
4,Plot 1,6.82,4.07,0.180,13.1,0.81,4.02,1.25,10.0,0.88,71.0
...,...,...,...,...,...,...,...,...,...,...,...
145,Plot 5,6.93,3.33,0.301,18.1,1.13,13.79,2.01,13.3,1.47,61.6
146,Plot 5,6.38,3.25,0.258,27.0,0.86,11.18,1.56,11.5,1.17,100.8
147,Plot 5,6.26,3.79,0.259,15.8,0.76,7.65,1.22,11.9,0.94,106.1
148,Plot 5,6.26,2.18,0.259,27.0,0.81,16.18,1.79,11.9,0.84,94.4
149,Plot 5,6.98,2.38,0.223,19.0,0.66,9.37,0.85,13.6,1.55,109.6